import { Router, Request, Response, NextFunction, RequestHandler } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const router = Router({ mergeParams: true }); // To access :companyId

// --- UpdateLog Routes ---

// POST /api/companies/:companyId/updatelogs - Create a new update log entry
router.post('/', (async (req: Request, res: Response, next: NextFunction) => {
  const { companyId } = req.params;
  const { fieldName, oldValue, newValue, source, userId } = req.body;

  if (!fieldName) {
    return res.status(400).json({ error: 'fieldName is required for the update log.' });
  }

  try {
    const newLogEntry = await prisma.updateLog.create({
      data: {
        companyId,
        fieldName,
        oldValue,
        newValue,
        source,
        userId,
        // timestamp is auto-generated by @default(now())
      },
    });
    res.status(201).json(newLogEntry);
  } catch (error) {
    console.error(`Error creating update log for company ${companyId}:`, error);
    if ((error as any).code === 'P2003') { // Foreign key constraint failed (companyId not found)
        return res.status(404).json({ error: `Company with ID ${companyId} not found.` });
    }
    res.status(500).json({ error: 'Failed to create update log entry' });
  }
}) as RequestHandler);

// GET /api/companies/:companyId/updatelogs - Get all update logs for a company
router.get('/', (async (req: Request, res: Response, next: NextFunction) => {
  const { companyId } = req.params;
  try {
    const logs = await prisma.updateLog.findMany({
      where: { companyId },
      orderBy: {
        timestamp: 'desc', // Show most recent logs first
      },
    });
    res.json(logs);
  } catch (error) {
    console.error(`Error fetching update logs for company ${companyId}:`, error);
    res.status(500).json({ error: 'Failed to fetch update logs' });
  }
}) as RequestHandler);

export default router;
